# Generated by Django 5.2 on 2025-05-10 14:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('vehicle_info', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('shipment_date', models.DateField(default=django.utils.timezone.now)),
                ('estimated_arrival', models.DateField(blank=True, null=True)),
                ('ripeness_status', models.CharField(choices=[('unripe', 'Unripe'), ('freshripe', 'Fresh Ripe'), ('ripe', 'Ripe'), ('overripe', 'Overripe'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('dominant_ripeness', models.CharField(choices=[('unripe', 'Unripe'), ('freshripe', 'Fresh Ripe'), ('ripe', 'Ripe'), ('overripe', 'Overripe'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('ripeness_summary', models.JSONField(blank=True, default=dict)),
                ('predictions', models.JSONField(blank=True, default=list)),
                ('shelf_life', models.CharField(blank=True, max_length=20)),
                ('alert_sent', models.BooleanField(default=False)),
                ('result_image', models.TextField(blank=True)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lon', models.FloatField(blank=True, null=True)),
                ('optimized_route', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shipments', to=settings.AUTH_USER_MODEL)),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.deliveryperson')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shipments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BananaImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_data', models.BinaryField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shipments.shipment')),
            ],
        ),
    ]
